### ISSUE TITLE
PR: Add support for `eslint-plugin-flowtype-errors`

### ISSUE THREAD

**Issue by amilajack** [olegakbarov/react-component-boilerplate#1]
This plugin reports flow errors as ESLint errors.

![ESLint Flow Demo](https://github.com/amilajack/eslint-plugin-flowtype-errors/blob/master/flow-demo.gif?raw=true)

Note: In this demo, I am using atom with the packages 'linter' and 'linter-eslint'

https://github.com/amilajack/eslint-plugin-flowtype-errors

**Comment by olegakbarov** [comment]
Yeah looks good to me, are you up to do it?

**Comment by amilajack** [comment]
Yup!
